version: '2.1'
services:
  elasticsearch:
    image: elasticsearch-image
    container_name: elasticsearch
    build: elasticsearch/
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    environment:
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - bootstrap.memory_local=true
      - cluster.name=adlp-cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - deploy_network

  kibana:
    image: kibana-image
    container_name: kibana
    build: kibana/
    depends_on:
      elasticsearch:
          condition: service_healthy
    ports:
     - "5601:5601"
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
     - XPACK_MONITORING_ENABLED=false
    networks:
     - deploy_network

  indexer:
    container_name: indexer
    build: indexer/
    restart: always
    networks:
      - deploy_network
    volumes:
      - .:/code
    depends_on:
      elasticsearch:
          condition: service_healthy

networks:
  deploy_network: