version: '2.1'
services:
  elasticsearch:
    container_name: elasticsearch
    build: elasticsearch/
    restart: always
    networks:
      - deploy_network
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    environment:
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - bootstrap.memory_local=true
      - cluster.name=adlp-cluster
    ports:
      - 19200:9200
      - 19300:9300

  kibana:
    container_name: kibana
    build: kibana/
    restart: always
    ports:
      - 5601:5601
    networks:
      - deploy_network
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:19200
      SERVER_NAME: http://localhost:5601
    depends_on:
      elasticsearch:
          condition: service_healthy

  indexer:
    container_name: indexer
    build: indexer/
    restart: always
    networks:
      - deploy_network
    depends_on:
      elasticsearch:
          condition: service_healthy

#  dashboard:
#    image: dashboard
#    volumes:
#      - .:/code
#    build:
#      context: .
#      dockerfile: ./dashboard/Dockerfile
#    restart: always
#    networks: [deploy_network]
#    environment:
#      - PORT=8050
#      - HOST=0.0.0.0
#    ports:
#      - "${DASHBOARD_PORT}:8050"
#    depends_on:
#      - elasticsearch
#      - kibana
#
networks:
  deploy_network: